name: Run Python Script Daily

on:
  schedule:
    - cron: '0 8 * * *'  # This runs the workflow every day at 8:00 AM UTC.
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI.

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python on the runner
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies, make sure to list them in requirements.txt

    - name: Run the Python script
      run: pokedata_scraper  # Run your Python script
